name: CI - Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Configuracao:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake build-essential

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Upload build directory
        uses: actions/upload-artifact@v4
        with:
          name: build-dir
          path: |
            build
            CMakeCache.txt
            CMakeFiles

  Compilacao:
    runs-on: ubuntu-latest
    needs: Configuracao
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build directory
        uses: actions/download-artifact@v4
        with:
          name: build-dir
          path: build

      - name: Build
        run: cmake --build build

      - name: Upload compiled build
        uses: actions/upload-artifact@v4
        with:
          name: compiled-build
          path: build

  Testes:
    runs-on: ubuntu-latest
    needs: Compilacao
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download compiled build
        uses: actions/download-artifact@v4
        with:
          name: compiled-build
          path: build

      - name: Run tests
        run: ./build/testes
