name: CI - Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Configuração:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake build-essential

      - name: Configure CMake
        run: cmake -S . -B build

  Compilação:
    runs-on: ubuntu-latest
    needs: Configuração
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build
        run: cmake --build build

  Testes:
    runs-on: ubuntu-latest
    needs: Compilação
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run tests
        run: ./build/testes
